version: "3.8"
services:
  db:
    image: postgres:latest
    ports: ["5432"]
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 1234567890
      POSTGRES_DB: test

  parrotwings:
    image: ${DOCKER_REGISTRY-}parrotwings
    ports:
      - "44357:80"
    networks:
      - backend
    depends_on:
      - db
    build:
      context: .
      dockerfile: ParrotWings/Dockerfile
    environment:
      DB_CONNECTION_STRING: "Host=db;Port=5432;Database=test;Username=test;Password=1234567890"

networks:
  backend:

volumes:
  db-data:
